name: Check for vulnerabilities daily

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *

permissions:
  contents: read
  issues: write

jobs:
  check-vulns:
    name: Check vulnerabilities on ${{ matrix.nsolidStream }}
    secrets: inherit
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        nsolidStream: ["node-v20.x-nsolid-v5.x", "node-v22.x-nsolid-v5.x"]
    uses: ./.github/workflows/check-vulns.yml
    with:
      nsolidStream: ${{ matrix.nsolidStream }}

